// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARUPUy2yEMow2JDn5cweNx3MpGGgP1TCM',
    appId: '1:203315352795:web:89b2e7038ea758c30268fe',
    messagingSenderId: '203315352795',
    projectId: 'smartcloset-95789',
    authDomain: 'smartcloset-95789.firebaseapp.com',
    storageBucket: 'smartcloset-95789.firebasestorage.app',
    measurementId: 'G-20ZSYVCX7R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLapgbcVq35Diga84GcpwWL8IYxEa2ZTg',
    appId: '1:203315352795:android:f37be4d46bf755070268fe',
    messagingSenderId: '203315352795',
    projectId: 'smartcloset-95789',
    storageBucket: 'smartcloset-95789.firebasestorage.app',
  );
  /// iOS Firebase yapılandırması.
  ///
  /// ⚠️  KULLANICI AKSİYONU GEREKLİ — aşağıdaki adımları izleyin:
  ///   1. Firebase Console → Project Settings → "Add app" → iOS
  ///   2. Bundle ID olarak girin: com.stilasist.stilAsist
  ///   3. GoogleService-Info.plist indirin
  ///   4. Xcode'da ios/Runner/ klasörüne sürükle-bırak ile ekleyin
  ///   5. GoogleService-Info.plist dosyasındaki değerleri aşağıya kopyalayın:
  ///      - API_KEY          → apiKey
  ///      - GOOGLE_APP_ID    → appId
  ///      - CLIENT_ID        → iosClientId
  ///      - GCG_SENDER_ID    → messagingSenderId (zaten: '203315352795')

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyoieET80PIAPt_hrlOoiZEhnKfStf-QU',
    appId: '1:203315352795:ios:9b79ec7a636df0dc0268fe',
    messagingSenderId: '203315352795',
    projectId: 'smartcloset-95789',
    storageBucket: 'smartcloset-95789.firebasestorage.app',
    iosClientId: '203315352795-ikfsq641mpl6nvsapn5td8ruc00999j9.apps.googleusercontent.com',
    iosBundleId: 'com.stilasist.stilAsist',
  );
}
